# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "uas" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f06b34ee-2d61-4326-a117-951403adc05e";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  # fileSystems."/swap" =
  #   { device = "/dev/disk/by-uuid/f06b34ee-2d61-4326-a117-951403adc05e";
  #     fsType = "btrfs";
  #     options = [ "subvol=@SWAP" ];
  #   };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CE2A-B8B3";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/f06b34ee-2d61-4326-a117-951403adc05e";
      fsType = "btrfs";
      options = [ "subvol=@HOME" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/f06b34ee-2d61-4326-a117-951403adc05e";
      fsType = "btrfs";
      options = [ "subvol=@VAR" ];
    };
    
  fileSystems."/mnt/Games" =
    { device = "/dev/disk/by-uuid/6a1c6c6f-a7cf-42d7-8112-7f175ba2d679";
      fsType = "ext4";
    };



  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
